package fr.univ_amu.iut.communication;

public enum Flags {
    BACK_TO_MENU,
    LOGIN,
    LOGIN_SUCCESSFULLY,
    LOGIN_NOT_SUCCESSFULLY,
    MODULES,
    MODULE_CHOICE,
    TRAINING,
    STORY,
    ANSWERS,
    SUMMARY,
    USER_POINTS,
    EMAIL,
    SOLO,
    MULTIPLAYER_CREATION,
    CODE,
    SESSION_EXISTS,
    SESSION_NOT_EXISTS,
    BEGIN,
    NEW_PLAYER,
    MULTIPLAYER_JOIN
}
